name = "LoweredCodeUtils"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.2.3"

[deps]
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"

[compat]
JuliaInterpreter = "0.8"
julia = "1"

[extras]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CBinding", "InteractiveUtils", "Parameters", "Test"]
